<?xml version="1.0"?>
<package format="3">
  <name>piper_control</name>
  <version>0.1.0</version>
  <description>Piper real robot control bridge for ROS2 + MoveIt (ros2_control hardware interface)</description>
  <maintainer email="dream@example.com">Dream</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <!-- C++ dependencies (hardware interface plugin) -->
  <depend>hardware_interface</depend>
  <depend>pluginlib</depend>
  <depend>rclcpp</depend>
  <depend>rclcpp_lifecycle</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
