/**:
  ros__parameters:
    robot_description_planning:
      default_velocity_scaling_factor: 0.2
      default_acceleration_scaling_factor: 0.2

      joint_limits:
        joint1:
          has_position_limits: true
          min_position: -2.6179
          max_position: 2.6179
          has_velocity_limits: true
          max_velocity: 0.8
          has_acceleration_limits: true
          max_acceleration: 2.0
        joint2:
          has_position_limits: true
          min_position: 0.0
          max_position: 3.14
          has_velocity_limits: true
          max_velocity: 0.8
          has_acceleration_limits: true
          max_acceleration: 2.0
        joint3:
          has_position_limits: true
          min_position: -2.697
          max_position: 0.0
          has_velocity_limits: true
          max_velocity: 0.8
          has_acceleration_limits: true
          max_acceleration: 2.0
        joint4:
          has_position_limits: true
          min_position: -1.745
          max_position: 1.745
          has_velocity_limits: true
          max_velocity: 0.8
          has_acceleration_limits: true
          max_acceleration: 2.0
        joint5:
          has_position_limits: true
          min_position: -1.22
          max_position: 1.22
          has_velocity_limits: true
          max_velocity: 0.8
          has_acceleration_limits: true
          max_acceleration: 2.0
        joint6:
          has_position_limits: true
          min_position: -2.09439
          max_position: 2.09439
          has_velocity_limits: true
          max_velocity: 0.8
          has_acceleration_limits: true
          max_acceleration: 2.0
        gripper_joint:
          has_position_limits: true
          min_position: 0.0
          max_position: 0.035
          has_velocity_limits: true
          max_velocity: 0.08
          has_acceleration_limits: true
          max_acceleration: 1.0
