/**:
  ros__parameters:
    planning_plugin: ompl_interface/OMPLPlanner
    default_planning_pipeline: ompl
    planning_pipelines:
      pipeline_names:
        - ompl
      namespace: ""
    ompl:
      planning_plugin: ompl_interface/OMPLPlanner
      request_adapters: "default_planner_request_adapters/AddRuckigTrajectorySmoothing default_planner_request_adapters/AddTimeOptimalParameterization default_planner_request_adapters/FixStartStateBounds default_planner_request_adapters/FixStartStateCollision"
      response_adapters: "default_planning_response_adapters/AddTimeOptimalParameterization default_planning_response_adapters/ValidateSolution default_planning_response_adapters/DisplayMotionPath"
      planner_configs:
        RRTConnectkConfigDefault:
          type: geometric::RRTConnect
          range: 0.0
        RRTkConfigDefault:
          type: geometric::RRT
          range: 0.0
          goal_bias: 0.05
        RRTstarkConfigDefault:
          type: geometric::RRTstar
          range: 0.0
          goal_bias: 0.05
          delay_collision_checking: 1
        PRMkConfigDefault:
          type: geometric::PRM
          max_nearest_neighbors: 10
        KPIECEkConfigDefault:
          type: geometric::KPIECE
          range: 0.0
          goal_bias: 0.05
          border_fraction: 0.9
          failed_expansion_score_factor: 0.5
          min_valid_path_fraction: 0.5
      manipulator:
        planner_configs:
          - RRTConnectkConfigDefault
          - RRTkConfigDefault
          - RRTstarkConfigDefault
          - PRMkConfigDefault
          - KPIECEkConfigDefault
