ros__parameters:
  update_rate: 50
  use_sim_time: false

  joint_state_broadcaster:
    type: joint_state_broadcaster/JointStateBroadcaster

  forward_position_controller:
    type: forward_command_controller/ForwardCommandController

forward_position_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
      - joint7
    interface_name: position
